"""add_reports_table

Revision ID: 013b428c173e
Revises: 7192373ad3b3
Create Date: 2026-03-08 12:46:03.292895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '013b428c173e'
down_revision: Union[str, None] = '7192373ad3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('report_type', postgresql.ENUM('prescription', 'lab_report', 'xray', 'discharge_summary', 'other', name='report_type'), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_appointment_id'), 'reports', ['appointment_id'], unique=False)
    op.create_index('ix_reports_org_appointment', 'reports', ['organization_id', 'appointment_id'], unique=False)
    op.create_index('ix_reports_org_patient', 'reports', ['organization_id', 'patient_id'], unique=False)
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reports_patient_id'), 'reports', ['patient_id'], unique=False)
    op.create_index('ix_reports_patient_type', 'reports', ['patient_id', 'report_type'], unique=False)
    op.create_index(op.f('ix_reports_uploaded_by'), 'reports', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_uploaded_by'), table_name='reports')
    op.drop_index('ix_reports_patient_type', table_name='reports')
    op.drop_index(op.f('ix_reports_patient_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_index('ix_reports_org_patient', table_name='reports')
    op.drop_index('ix_reports_org_appointment', table_name='reports')
    op.drop_index(op.f('ix_reports_appointment_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
