"""add_heart_rate_to_patients

Revision ID: 1814c1f0fe94
Revises: 45a99d56cf41
Create Date: 2026-03-27 12:49:52.705778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1814c1f0fe94'
down_revision: Union[str, None] = '45a99d56cf41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('heart_rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'heart_rate')
    # ### end Alembic commands ###
