"""add_booking_fields_and_doctor_schedule

Revision ID: 1973215b1c0c
Revises: dbffe0e29e75
Create Date: 2026-03-15 14:30:46.968865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1973215b1c0c'
down_revision: Union[str, None] = 'dbffe0e29e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_schedules',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'day_of_week', name='uq_doctor_schedule_day')
    )
    op.create_index(op.f('ix_doctor_schedules_doctor_id'), 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_organization_id'), 'doctor_schedules', ['organization_id'], unique=False)
    op.add_column('appointments', sa.Column('booking_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_appointments_booking_id'), 'appointments', ['booking_id'], unique=True)
    op.add_column('organizations', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'address')
    op.drop_index(op.f('ix_appointments_booking_id'), table_name='appointments')
    op.drop_column('appointments', 'booking_id')
    op.drop_index(op.f('ix_doctor_schedules_organization_id'), table_name='doctor_schedules')
    op.drop_index(op.f('ix_doctor_schedules_doctor_id'), table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    # ### end Alembic commands ###
