"""add audit_log

Revision ID: 2026_05_01_add_audit_log
Revises: 
Create Date: 2026-05-01 01:23:18.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2026_05_01_add_audit_log'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'audit_log',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('doctor_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('appointment_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index('ix_audit_patient_created', 'audit_log', ['patient_id', 'created_at'])
    op.create_index('ix_audit_doctor_created', 'audit_log', ['doctor_id', 'created_at'])
    op.create_index('ix_audit_appointment', 'audit_log', ['appointment_id'])

    # ✅ FIX FOR consultation_notes
    from sqlalchemy import inspect

    bind = op.get_bind()
    inspector = inspect(bind)

    if "consultation_notes" not in inspector.get_table_names():
        op.create_table(
            "consultation_notes",
            sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
            sa.Column("doctor_id", postgresql.UUID(as_uuid=True)),
            sa.Column("patient_id", postgresql.UUID(as_uuid=True)),
            sa.Column("content", sa.Text),
            sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
            sa.Column("created_at", sa.DateTime(timezone=True)),
            sa.Column("updated_at", sa.DateTime(timezone=True)),
        )
    else:
        op.add_column(
            "consultation_notes",
            sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultation_notes', 'version')
    op.drop_index('ix_audit_appointment', table_name='audit_log')
    op.drop_index('ix_audit_doctor_created', table_name='audit_log')
    op.drop_index('ix_audit_patient_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###