"""add_name_phone_to_users_phone_email_website_to_orgs

Revision ID: 45a99d56cf41
Revises: f3a9b2c1d4e5
Create Date: 2026-03-16 23:46:51.203549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45a99d56cf41'
down_revision: Union[str, None] = 'f3a9b2c1d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    # ### end Alembic commands ###
