"""add doctors table

Revision ID: 5df8f7684c46
Revises: 5f2de77f86d5
Create Date: 2026-03-01 02:01:15.005909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5df8f7684c46'
down_revision: Union[str, None] = '5f2de77f86d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gender', postgresql.ENUM('male', 'female', 'other', name='doctor_gender'), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('employment_type', postgresql.ENUM('full_time', 'part_time', 'visiting', name='doctor_employment_type'), nullable=False),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'on_duty', 'on_call', 'on_leave', 'inactive', name='doctor_status'), nullable=False),
    sa.Column('staff_record', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'license_number', name='uq_doctors_org_license')
    )
    op.create_index('ix_doctors_org_specialization', 'doctors', ['organization_id', 'specialization'], unique=False)
    op.create_index('ix_doctors_org_status', 'doctors', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_doctors_organization_id'), 'doctors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_doctors_specialization'), 'doctors', ['specialization'], unique=False)
    op.create_index(op.f('ix_doctors_status'), 'doctors', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_status'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_specialization'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_organization_id'), table_name='doctors')
    op.drop_index('ix_doctors_org_status', table_name='doctors')
    op.drop_index('ix_doctors_org_specialization', table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
