"""fix circular fk

Revision ID: 5f2de77f86d5
Revises: dc90cf5471b4
Create Date: 2026-02-28 21:26:42.701138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f2de77f86d5'
down_revision: Union[str, None] = 'dc90cf5471b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('organizations_created_by_fkey', 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key('organizations_created_by_fkey', 'organizations', 'users', ['created_by'], ['id'])
    op.alter_column('organizations', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
