"""add_appointments_table

Revision ID: 7192373ad3b3
Revises: dd4b4b7bd9c9
Create Date: 2026-03-02 15:22:40.572356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7192373ad3b3'
down_revision: Union[str, None] = 'dd4b4b7bd9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create enum types first (create_type=False in model means Alembic won't auto-emit these)
    op.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'appointment_status') THEN
                CREATE TYPE appointment_status AS ENUM ('scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled');
            END IF;
        END $$;
    """))
    op.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'appointment_type') THEN
                CREATE TYPE appointment_type AS ENUM ('walk_in', 'scheduled');
            END IF;
        END $$;
    """))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('appointment_type', postgresql.ENUM('walk_in', 'scheduled', name='appointment_type', create_type=False), server_default='scheduled', nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', name='appointment_status', create_type=False), server_default='scheduled', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('token_number', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_organization_id'), 'appointments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appt_org_date', 'appointments', ['organization_id', 'appointment_date'], unique=False)
    op.create_index('ix_appt_org_doctor_date', 'appointments', ['organization_id', 'doctor_id', 'appointment_date'], unique=False)
    op.create_index('ix_appt_org_patient', 'appointments', ['organization_id', 'patient_id'], unique=False)
    op.create_index('ix_appt_org_status', 'appointments', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appt_org_status', table_name='appointments')
    op.drop_index('ix_appt_org_patient', table_name='appointments')
    op.drop_index('ix_appt_org_doctor_date', table_name='appointments')
    op.drop_index('ix_appt_org_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_organization_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.execute("DROP TYPE IF EXISTS appointment_status")
    op.execute("DROP TYPE IF EXISTS appointment_type")
    # ### end Alembic commands ###
