"""add_medical_history_table

Revision ID: 8355ccd5f875
Revises: 013b428c173e
Create Date: 2026-03-08 22:44:39.619842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8355ccd5f875'
down_revision: Union[str, None] = '013b428c173e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_history',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_history_appointment_id'), 'medical_history', ['appointment_id'], unique=False)
    op.create_index('ix_medical_history_org_patient', 'medical_history', ['organization_id', 'patient_id'], unique=False)
    op.create_index(op.f('ix_medical_history_organization_id'), 'medical_history', ['organization_id'], unique=False)
    op.create_index('ix_medical_history_patient_date', 'medical_history', ['patient_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_medical_history_patient_id'), 'medical_history', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_history_patient_id'), table_name='medical_history')
    op.drop_index('ix_medical_history_patient_date', table_name='medical_history')
    op.drop_index(op.f('ix_medical_history_organization_id'), table_name='medical_history')
    op.drop_index('ix_medical_history_org_patient', table_name='medical_history')
    op.drop_index(op.f('ix_medical_history_appointment_id'), table_name='medical_history')
    op.drop_table('medical_history')
    # ### end Alembic commands ###
