"""add_patient_auth_and_junction_table

Revision ID: 9c3a4e898c9d
Revises: 8355ccd5f875
Create Date: 2026-03-11 02:42:03.935063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c3a4e898c9d'
down_revision: Union[str, None] = '8355ccd5f875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_organizations',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'organization_id', name='uq_patient_org')
    )
    op.create_index(op.f('ix_patient_organizations_organization_id'), 'patient_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_patient_organizations_patient_id'), 'patient_organizations', ['patient_id'], unique=False)
    op.add_column('patients', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'patients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'hashed_password')
    op.drop_index(op.f('ix_patient_organizations_patient_id'), table_name='patient_organizations')
    op.drop_index(op.f('ix_patient_organizations_organization_id'), table_name='patient_organizations')
    op.drop_table('patient_organizations')
    # ### end Alembic commands ###
