"""make_patient_org_id_and_gender_nullable

Revision ID: a473c18e8033
Revises: 9c3a4e898c9d
Create Date: 2026-03-11 03:05:43.812778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a473c18e8033'
down_revision: Union[str, None] = '9c3a4e898c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('patients', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='patient_gender'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'gender',
               existing_type=postgresql.ENUM('male', 'female', 'other', name='patient_gender'),
               nullable=False)
    op.alter_column('patients', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
