"""add booking_draft to patients

Revision ID: c673c1a76aa8
Revises: 2a7f3e9b1c05
Create Date: 2026-03-29 21:58:14.660908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c673c1a76aa8'
down_revision: Union[str, None] = '2a7f3e9b1c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('booking_draft', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'booking_draft')
    # ### end Alembic commands ###
