"""add_otp_records_table

Revision ID: dbffe0e29e75
Revises: a473c18e8033
Create Date: 2026-03-11 03:47:43.163188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dbffe0e29e75'
down_revision: Union[str, None] = 'a473c18e8033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_records',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_records_patient_id'), 'otp_records', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_records_patient_id'), table_name='otp_records')
    op.drop_table('otp_records')
    # ### end Alembic commands ###
