"""test base structure

Revision ID: dc90cf5471b4
Revises: a3f1c9d82b45
Create Date: 2026-02-28 21:22:58.858016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc90cf5471b4'
down_revision: Union[str, None] = 'a3f1c9d82b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
