"""add_patient_code_column

Revision ID: dd4b4b7bd9c9
Revises: a372fea3c1a4
Create Date: 2026-03-02 02:09:41.342040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd4b4b7bd9c9'
down_revision: Union[str, None] = 'a372fea3c1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('patient_code', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=False)
    op.create_unique_constraint('uq_patients_org_code', 'patients', ['organization_id', 'patient_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_patients_org_code', 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_column('patients', 'patient_code')
    # ### end Alembic commands ###
